[tool.black]
line_length = 100

[tool.isort]
honor_noqa = true
line_length = 100
profile = "black"
verbose = false

known_first_party = [
	# all folders you want to lump
  "src",
]

# Block below is google style import formatting https://pycqa.github.io/isort/docs/configuration/profiles.html
force_sort_within_sections = true
force_single_line = true
lexicographical = true
single_line_exclusions = ["typing"]
order_by_type = false
group_by_package = true
