name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./aws/Dockerfile
        context: ./aws
        tags: ${{ secrets.DOCKER_USERNAME }}/imgdataset:latest,${{ secrets.DOCKER_USERNAME }}/imgdataset:${{ github.sha }}

    - name: Output image name
      run: |
        echo "Image URI: ${{ secrets.DOCKER_USERNAME }}/imgdataset:${{ github.sha }}"
